ARG BASE_VERSION=latest
ARG BASE=corpusops/nginx
FROM $BASE:$BASE_VERSION as base
ADD docker-images/rootfs/bin/ /bin/
ARG SUPERVISORD_CONFIGS="rsyslog cron nginx"
ENV SUPERVISORD_CONFIGS=$SUPERVISORD_CONFIGS
USER root
ENTRYPOINT ["/bin/supervisord.sh"]
