env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  BUILDKIT_PROGRESS: "plain"
  NO_SQUASH: ""
  RELEASABLE_REPOS: "^corpusops/"
  RELEASABLE_BRANCHES: "^(refs/heads/)?(master|main|workflows)$"
jobs:
  r:
    runs-on: ubuntu-24.04
    env: {IMG: "${{matrix.IMG}}",
          DFILE: "${{matrix.DFILE}}",
          DPATH: "${{matrix.DPATH}}",
          NGINX: "${{matrix.NGINX}}",
          IMG_FLAVOR: "${{matrix.IMG_FLAVOR}}",}
    steps:
      - name: Set vars
        run: |-
            if ( echo "$GITHUB_REF" | egrep -q "${RELEASABLE_BRANCHES}" ) \
            && ( echo "$GITHUB_REPOSITORY" | egrep -q "${RELEASABLE_REPOS}" )
            then releasable=true;else releasable=false;fi
            echo "releasable=$releasable" >> $GITHUB_OUTPUT
            echo "silent=$(echo $silent)" >> $GITHUB_OUTPUT
        id: v
      - uses: docker/login-action@v2
        with: {username: "${{ secrets.DOCKER_HUB_USERNAME }}", password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"}
      - name: Activate docker experimental
        run: |-
          sudo bash -exc "if [ ! -e /etc/docker/daemon.json ];then mkdir /etc/docker||true;echo '{}' > /etc/docker/daemon.json;fi;service docker stop;python -c \"d='/etc/docker/daemon.json';\
          import json;c=json.load(open(d));c['experimental']=True;\
          open(d, 'w').write(json.dumps(c))\";systemctl restart docker"
      - uses: actions/checkout@v3
      - name: build & release
        run: |-
          set -ex
          ./refresh.sh
          db() {
            docker build \
             --build-arg BASE="$BASE" --build-arg BASE_VERSION="$BASE_VERSION" \
             --build-arg BUILDKIT_INLINE_CACHE="1" -t ${3} -f ${1} ${2} "${@:4}"
          }
          results=/tmp/result;touch $results
          for img_flavor in ${IMG_FLAVORS-} ${IMG_FLAVOR-};do
            BASE=$(echo $img_flavor        |sed -r -e "s/^helpers-?//g" -e "s/-.*//g" \
                                                   -e "s/(nginx|ubuntu|centos|alpine|debian)/corpusops\/\1/g" \
                                                   -e "s/(ubuntu|centos|alpine|debian)/\1-bare/g" \
                                                   -e "s/^$/ubuntu/g" )
            BASE_VERSION=$(echo $img_flavor|sed -r -e "s!^(helpers-)?(nginx|centos|ubuntu|debian|alpine)?-?!!g" \
                                                   -e "s/^(helpers)?$/latest/g" )
            t=${IMG}:${img_flavor}
            if !(db ${DFILE} ${DPATH} ${t}-no-squash;docker tag ${t}-no-squash ${t});then
              echo "$IMG $img_flavor" > $results
            else
              if [ "x${{steps.v.outputs.releasable}}" = "xtrue" ];then for i in "" -no-squash;do docker push ${t}${i};done;fi
              if [ "x${NO_SQUASH}" = "x" ];then db ${DFILE} ${DPATH} ${t} --squash;fi
            fi
          done
          if [ "x$(cat $results)" != "x" ];then cat $results;exit 1;fi
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        include:
        - {IMG_FLAVOR: "helpers
                        helpers-ubuntu
                        helpers-ubuntu-jammy
                        helpers-ubuntu-trusty helpers-ubuntu-xenial
                        helpers-ubuntu-bionic helpers-ubuntu-focal
                        helpers-ubuntu-22.04 helpers-ubuntu-24.04
                        helpers-ubuntu-18.04 helpers-ubuntu-16.04
                        helpers-ubuntu-14.04",
           IMG: "corpusops/project", DFILE: "Dockerfile.helpers",  DPATH: "."}
        - {IMG_FLAVOR: "helpers-alpine helpers-alpine-3",
           IMG: "corpusops/project", DFILE: "Dockerfile.helpers",  DPATH: "."}
        - {IMG_FLAVOR: "helpers-centos-stream  helpers-centos
                        helpers-centos-stream9 helpers-centos-9
                        helpers-centos-stream8 helpers-centos-8
                        helpers-centos-7",
           IMG: "corpusops/project", DFILE: "Dockerfile.helpers",  DPATH: "."}
        - {IMG_FLAVOR: "helpers-debian helpers-debian-11
                        helpers-debian-10 helpers-debian-9",
           IMG: "corpusops/project", DFILE: "Dockerfile.helpers",  DPATH: "."}
        - {IMG_FLAVOR: "dbsetup",
           IMG: "corpusops/project", DFILE: "Dockerfile.dbsetup",  DPATH: "."}
        - {IMG_FLAVOR: "nginx nginx-alpine nginx-stable nginx-stable-alpine",
           IMG: "corpusops/project", DFILE: "Dockerfile.nginx",    DPATH: "."}
        - {IMG_FLAVOR: "mailhog",
           IMG: "corpusops/project", DFILE: "Dockerfile.mailhog",  DPATH: "."}
on:
  # push:
  # workflow_dispatch:
  # schedule: [{cron: '1 0 1,3,5,15,17,19 * *'}]
